name: Publish
on:
  push:
    branches:
    - main

jobs:
  publish_to_website:
    name: Publish on davidwesst.com
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Website Publish
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: davidwesst/website
        token: ${{ secrets.WEBSITE_ACCESS_TOKEN }}
        event-type: blog-update
        client-payload: '{ "sha": "${{ github.sha }}" }'
