name: CI/CD 

on:
  push:
    branches:
      - main
      - ft/*
      - hf/*
      - v11
      - '!post/**'
    paths-ignore:
      - 'docs/**/*'
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/* 

      - name: Set Path Prefix
        if: false
        run: echo "SITE_PATH_PREFIX=website" >> $GITHUB_ENV

      - name: Build
        id: build
        run: |
          npm install
          npm run build

      - name: Run Playwright Tests
        id: test
        run: |
          npx playwright install --with-deps
          npx playwright test --reporter=html
        env:
          CI: true

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: playwright-report/index.html
          if-no-files-found: error

      - name: Upload Site Files as Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          retention-days: 1

  deploy:
    name: Deploy
    if: github.ref_name == 'hf/broken-images'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
