name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update --remote --merge
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn install --legacy-peer-deps
    - run: yarn run build
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: public/
  publish:
    name: Publish Website
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: website
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./website
          cname: www.davidwesst.com
          commit_message: ${{ github.event.head_commit.message }}


 
      
