name: CI/CD 

on:
  push:
    branches:
      - main
      - ft/*
      - hf/*
      - '!post/**'
    paths-ignore:
      - 'docs/**/*'
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/* 

      - name: Generate DotEnv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: "DOTENV_"
        env:
          DOTENV_AI_CONNECTION_STRING: ${{ secrets.AI_CONNECTION_STRING }}

      - name: Set Path Prefix
        run: echo "SITE_PATH_PREFIX=website" >> $GITHUB_ENV

      - name: Build
        id: build
        run: |
          npm install
          npm run build

      - name: Upload Site Files as Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          retention-days: 1

  deploy:
    name: Deploy
    if: github.ref_name == 'main' || github.ref_name == 'hf/asset-pathprefix'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
